.PHONY: clean All

All:
	@echo "----------Building project:[ HW - Debug ]----------"
	@cd "HW" && "$(MAKE)" -f  "HW.mk"
clean:
	@echo "----------Cleaning project:[ HW - Debug ]----------"
	@cd "HW" && "$(MAKE)" -f  "HW.mk" clean
